title_primary: "LImoritakeU" # the bigger text
title_secondary: "這程式需要更多咖啡因" # the smaller text
keywords:

rss: atom.xml
github: LImoritakeU

# Choose the comment service according to your need.
# Please do not use the two services at the same time.
livere: # [data-uid] on livere.com
disqus: https-www-limoritakeu-tech # [short_name] on disqus.com
dove: # For fun ONLY. Set to true to 'disable' comments on your site.

# Set true to show the page indicator.
showPageCount: true

# Set true to show category or tags behind post titles
showCategories: true
showTags: true

# Color scheme
themeStyle: light # light/dark
